### ISSUE TITLE
AWS Toolkit default region set to deployed region?

### ISSUE THREAD

**Issue by charlesshen** [vgribok/AWS-EC2-Windows-Dev-Init#1]
Hi Vlad,

Is there any way for the VM to be self aware of the region it is deployed in and then default the AWS Toolkit region to match it?   This AMI is available on multiple regions and Event Engine does not like it when your event is in a certain region and you create resources in a different region (surprisingly resources get created, but the web console blocks off users from accessing the outside region).

This is not a critical issue, but I can see it potentially preventing botched resource creation when users forget to switch to the allowed region.

**Comment by vgribok** [comment]
Charlie,
The ec2 instance is well aware of its region - the script gets that data from the instance metadata service. But my brief search didn't yield a way to force VS rollout to pick a that region. AWS SDK default region selection available via powershell does not seem to make any difference for vs toolkit. If you find how to do this, please let me know or send a PR!

**Comment by charlesshen** [comment]
Hi Vlad,  I can confirm that you will find the default selected AWS Toolkit region in the file 

C:\Users\Administrator\AppData\Local\AWSToolkit\MiscSettings.json

**Comment by charlesshen** [comment]
Specifically its the "lastselectedregion" property
```json
{
    "MiscSettings" : {
        "AnalyticsCognitoIdentityId" : "",
        "AnalyticsMostRecentlyUsedCognitoIdentityPoolId" : "us-east-1:0ab25aed-7bb5-47df-9b30-df1aa3ec1bd3",
        "AnalyticsAnonymousCustomerId"                   : "da2b7f8d-e7c3-4418-9cf6-3275a046e27e",
        "lastselectedregion"                             : "me-south-1",
        "LastAcountSelectedKey"                          : "549c79d7-0b36-4f1a-bf8c-4d3c49b8c84c"
    }
}
```

**Comment by vgribok** [comment]
Great, thanks, Charlie. I'll try to add this to the script ASAP.

**Comment by charlesshen** [comment]
Great to hear, thanks!

**Comment by vgribok** [comment]
Reopening until this is actually fixed.
